# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Call alias_c function from C
#'
#' @param x A vector of unnormalized probabilities
#' @param n_draws Integer number of draws from the discrete distribution
#' @return
#' An integer-valued vector of draws from the discrete distribution
#' @export
alias_cpp <- function(x, n_draws) {
    .Call(`_RHESSIAN_alias_cpp`, x, n_draws)
}

