# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Call alias_c function from C
#'
#' @param x A vector of unnormalized probabilities
#' @param n_draws Integer number of draws from the discrete distribution
#' @return
#' An integer-valued vector of draws from the discrete distribution
#' @export
alias_cpp <- function(x, n_draws) {
    .Call(`_RHESSIAN_alias_cpp`, x, n_draws)
}

#' Call skew_eval_c function in skew.c
#'
#' @param mode A scalar, the mode of the target distribution
#' @param h A vector, the first five derivatives of the log target distribution
#' @param mu A scalar, the prior mean
#' @param omega A scalar, the prior precision
#' @param z A vector of points of evaluation
#' @return
#' A vector of evaluations of the log normalized target density
#' @export
skew_eval_cpp <- function(mode, h, mu, omega, z) {
    .Call(`_RHESSIAN_skew_eval_cpp`, mode, h, mu, omega, z)
}

#' Call skew_draw_c function in skew.c
#'
#' @param mode A scalar, the mode of the target distribution
#' @param h A vector, the first five derivatives of the log target distribution
#' @param mu A scalar, the prior mean
#' @param omega A scalar, the prior precision
#' @param n_draws A scalar integer, the number of draws to make
#' @return
#' A vector of draws from the target distribution
#' @export
skew_draw_cpp <- function(mode, h, mu, omega, n_draws) {
    .Call(`_RHESSIAN_skew_draw_cpp`, mode, h, mu, omega, n_draws)
}

#' Call C language spline_eval_c function
#'
#' @param p A vector of levels on grid
#' @param m A vector of derivatives on grid
#' @param u A vector of values at which to evaluate a spline density
#' @return
#' The vector of spline density values
#' @export
spline_eval_cpp <- function(p, m, u) {
    .Call(`_RHESSIAN_spline_eval_cpp`, p, m, u)
}

#' Call C language spline_draw_c function
#'
#' @param p A vector of levels on grid
#' @param m A vector of derivatives on grid
#' @param n_draws The number of draws to make from the spline density
#' @return
#' The vector of spline density draws
#' @export
spline_draw_cpp <- function(p, m, n_draws) {
    .Call(`_RHESSIAN_spline_draw_cpp`, p, m, n_draws)
}

